### ISSUE TITLE
Load generator: verify reachability of clients through the chrome remote debugger

### ISSUE THREAD

**Issue by aleskandro** [mora-resource-allocation-edge-cloud/mora#11]
1. Execute the load generator
2. Configure your chrome browser to discover remote targets on ports in the range [9222, 9222 + $MAX_EXPOSED_PORTS], where $MAX_EXPOSED_PORTS is the env variable described in #10. At row [https://github.com/mora-resource-allocation-edge-cloud/load-generator/blob/5d1cadc7b97c2868f521c1995a1144d5044d4ad6/main.go#L47](47 of the main.go), change the hard-coded 128 to the value of the env variable (conf.MaxExposedPorts) and set the default value of this varaible to 128
3. Check if you can reach the js console and the whole page view

**Comment by zazim13** [comment]
Hi @aleskandro. I just change the value of MaxExposedPorts to 128 and the loop condition also. It is working as before . 
But I am not sure about what I should see in the debugger. I can see urls where the video is available.

**Comment by andreaaraldo** [comment]
@aleskandro , we are remarking that maybe 128 ports are too few.

If the request rate is 5 videos/sec (with exponentially random distribution) and each video if 20 seconds, then on average we would concurrently use 100 ports (but, due to randomness, it is quite likely that in some extreme cases we would need more than 128 ports in the load generator). 
@zazim13  experienced some `websocket url timeout reached`, which may due to this.

@aleskandro , is there any reason why you suggest 128 or can we increase this limit to 512?
