### ISSUE TITLE
Clarification needed about variants

### ISSUE THREAD

**Issue by andreaaraldo** [mora-resource-allocation-edge-cloud/mora#4]
The documentation talks about three variants (see [this section](https://github.com/mora-resource-allocation-edge-cloud/mora/blob/minikubebranch/README.md#variants-and-options)).

However, the code shows completely different variants (see [these lines](https://github.com/mora-resource-allocation-edge-cloud/videomanagement/blob/6498f6ceab319820063c0dafb0b5dc5d6a80b080/src/main/java/com/arenalocastro/videomanagement/services/CloudEdgeService.java#L87))

@zazim13  and me were not able to understand what corresponds to what.

@aleskandro , could you please modify the documentation in order to match the code (or vice-versa).

I also added some questions in that section. Could you please integrate the information asked by those questions in that section of the doc?

The last version of the documentation is in the minikube branch.

Thx

**Comment by aleskandro** [comment]
Just writing here for the moment: I'll update soon the docs.

- Cloud Variant: trivially, the Cloud version of the application (whole set of microservices will be deployed and VMS will consider them available in its local network). This variant is managed by the `isCloud` environment variable

if isCloud is false:
- Cache variant (0): just download the whole encoded representations from the Cloud when a request comes to the edge
- Offline variant (1): download the raw mp4 video from the Cloud, then asks to the VPS in the edge for encoding in dash format
- Online variant (2): download the raw mp4 and use online encoding when requests come to the edge. This is not documented yet because it's a WIP: just a bit of code around there but not tested.

Shall we say there are 4 variants?

**Comment by andreaaraldo** [comment]
I suggest we say there are 4 variants: 
- In the cloud one MUST deploy the cloud variant
- In the edge, one can deploy one variant among {Cache Variant, Offline Variant, Online Variant}

I think like this it would be clear.

If you agree, could you please update the doc accordingly?
